// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuZpWnRf0EgfAOq0axuhvZsbbTnIuT2Gw',
    appId: '1:703615843516:web:6a7f9a725c1f4bd0ace4b9',
    messagingSenderId: '703615843516',
    projectId: 'lab5-27e91',
    authDomain: 'lab5-27e91.firebaseapp.com',
    databaseURL: 'https://lab5-27e91-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lab5-27e91.firebasestorage.app',
    measurementId: 'G-T4C91VF0M1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJwxpTPeTyWM3yotW4IfnU2lTg6HOKe9M',
    appId: '1:703615843516:ios:3a3f76a37cbd928dace4b9',
    messagingSenderId: '703615843516',
    projectId: 'lab5-27e91',
    databaseURL: 'https://lab5-27e91-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lab5-27e91.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJwxpTPeTyWM3yotW4IfnU2lTg6HOKe9M',
    appId: '1:703615843516:ios:3a3f76a37cbd928dace4b9',
    messagingSenderId: '703615843516',
    projectId: 'lab5-27e91',
    databaseURL: 'https://lab5-27e91-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lab5-27e91.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_t7cFyiSXC-V6P4RO8LO-_UUAtLZaH5A',
    appId: '1:703615843516:web:4729313f16656260ace4b9',
    messagingSenderId: '703615843516',
    projectId: 'lab5-27e91',
    authDomain: 'lab5-27e91.firebaseapp.com',
    databaseURL: 'https://lab5-27e91-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lab5-27e91.firebasestorage.app',
    measurementId: 'G-6WHTPZ8YYB',
  );
}
