// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// 
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_t7cFyiSXC-V6P4RO8LO-_UUAtLZaH5A',
    appId: '1:703615843516:web:4729313f16656260ace4b9',
    messagingSenderId: '703615843516',
    projectId: 'lab5-27e91',
    authDomain: 'lab5-27e91.firebaseapp.com',
    databaseURL: 'https://lab5-27e91-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lab5-27e91.firebasestorage.app',
    measurementId: 'G-6WHTPZ8YYB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJwxpTPeTyWM3yotW4IfnU2lTg6HOKe9M',
    appId: '1:703615843516:ios:79f83c894e67d312ace4b9',
    messagingSenderId: '703615843516',
    projectId: 'lab5-27e91',
    databaseURL: 'https://lab5-27e91-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lab5-27e91.firebasestorage.app',
    iosBundleId: 'com.example.motoManagerMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJwxpTPeTyWM3yotW4IfnU2lTg6HOKe9M',
    appId: '1:703615843516:ios:79f83c894e67d312ace4b9',
    messagingSenderId: '703615843516',
    projectId: 'lab5-27e91',
    databaseURL: 'https://lab5-27e91-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lab5-27e91.firebasestorage.app',
    iosBundleId: 'com.example.motoManagerMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_t7cFyiSXC-V6P4RO8LO-_UUAtLZaH5A',
    appId: '1:703615843516:web:dd93fae34e4ccf78ace4b9',
    messagingSenderId: '703615843516',
    projectId: 'lab5-27e91',
    authDomain: 'lab5-27e91.firebaseapp.com',
    databaseURL: 'https://lab5-27e91-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lab5-27e91.firebasestorage.app',
    measurementId: 'G-E5WYDMREWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1_RCCGVYaTHhevwcFDWsb5IsV4Kl5Hjg',
    appId: '1:703615843516:android:03fab6c6021f02e8ace4b9',
    messagingSenderId: '703615843516',
    projectId: 'lab5-27e91',
    databaseURL: 'https://lab5-27e91-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lab5-27e91.firebasestorage.app',
  );

}